# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'restcomm-helloworld' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  #use_frameworks!

  # Pods for restcomm-helloworld
  pod 'RestCommClient', :path => '../../'
  #pod 'RestCommClient'

  target 'restcomm-helloworldTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
