# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'restcomm-olympus' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for restcomm-olympus
  pod 'restcomm-ios-sdk', :path => '../../'
  #pod 'restcomm-ios-sdk'

  #target 'restcomm-olympusTests' do
  #  inherit! :search_paths
  #  # Pods for testing
  #end

end
