#use_frameworks!
platform :ios, '8.0'

target 'Sample' do

  # Temporary, these should reside in podspec
  #pod 'sofia-sip-library'
  #pod 'BoringSSL'
  #pod 'Quickblox-WebRTC'
  #pod 'webrtc-framework'

  #use_frameworks!
  #pod 'restcomm-ios-sdk', :path => '../'
  pod 'restcomm-ios-sdk'

  target 'Sample_Tests' do
    inherit! :search_paths

    #pod 'sofia-sip-library'
    #pod 'BoringSSL'
    #pod 'webrtc-framework'

    #pod 'restcomm-ios-sdk', :path => '../'
	 pod 'restcomm-ios-sdk'
    ##pod 'RestCommClient', :path => '../'
    #use_frameworks!

    #pod 'Specta'
    #pod 'Expecta'
    #pod 'FBSnapshotTestCase'
    #pod 'Expecta+Snapshots'
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
